version: "3"
services:

  appmetrics:
    image: node_app:latest
    ports:
      - "3000:3000"

  swiftmetrics:
    image: swift_app:latest
    ports:
      - "8080:8080"

  javametrics:
    image: java_app:latest
    ports:
      - "9080:9080"

#  wrk2:
#    image: workload_driver:latest
#    depends_on:
#      - swiftmetrics
#      - appmetrics
#      - javametrics
